// react/components/api-docs.tsx
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

const apiDocs = [
  {
    title: "概览接口",
    endpoint: "/api/v1/runtime/overview",
    method: "GET",
    description: "返回环境与渠道的树形结构",
    usage: "用于动态构建环境/渠道选择器",
  },
  {
    title: "实时接口（推荐）",
    endpoint: "/api/v1/runtime/config",
    method: "GET",
    description: "Header 传 x-environment, x-pipeline",
    usage: "需要实时获取最新配置的应用",
    recommended: true,
  },
  {
    title: "静态导出",
    endpoint: "/api/v1/runtime/static",
    method: "GET",
    description: "参数: ?environment_key=xxx&pipeline_key=xxx",
    usage: "离线部署、静态托管、CDN 分发",
  },
]

export function ApiDocs() {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-lg">前端对接</CardTitle>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {apiDocs.map((api) => (
            <div
              key={api.endpoint}
              className="p-4 rounded-lg border bg-card space-y-2"
            >
              <div className="flex items-center gap-2">
                <h4 className="font-medium">{api.title}</h4>
                {api.recommended && (
                  <Badge className="bg-emerald-100 text-emerald-800 dark:bg-emerald-900 dark:text-emerald-300">
                    推荐
                  </Badge>
                )}
              </div>
              <div className="flex items-center gap-2">
                <Badge variant="outline" className="font-mono text-xs">
                  {api.method}
                </Badge>
                <code className="text-sm font-mono text-muted-foreground bg-muted px-2 py-1 rounded">
                  {api.endpoint}
                </code>
              </div>
              <p className="text-sm text-muted-foreground">
                <strong>请求：</strong>
                {api.description}
              </p>
              <p className="text-sm text-muted-foreground">
                <strong>场景：</strong>
                {api.usage}
              </p>
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  )
}

// vue/src/components/ApiDocs.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Copy, Check, ExternalLink } from 'lucide-vue-next'
import { toast } from 'vue-sonner'

const copiedIndex = ref<number | null>(null)

const apiEndpoints = [
  {
    method: 'GET',
    path: '/api/v1/runtime/overview',
    description: '获取运行时概览（环境和渠道列表）',
  },
  {
    method: 'GET',
    path: '/api/v1/runtime/config',
    description: '获取运行时配置',
  },
  {
    method: 'POST',
    path: '/api/v1/runtime/static',
    description: '实时获取运行时状态',
  },
]

const methodColors: Record<string, string> = {
  GET: 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300',
  POST: 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-300',
  PUT: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-300',
  DELETE: 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-300',
}

const copyPath = async (path: string, index: number) => {
  await navigator.clipboard.writeText(path)
  copiedIndex.value = index
  toast.success('已复制到剪贴板')
  setTimeout(() => {
    copiedIndex.value = null
  }, 2000)
}
</script>

<template>
  <Card>
    <CardHeader>
      <div class="flex items-center justify-between">
        <CardTitle class="text-lg">前端对接</CardTitle>
        <a
          href="/api/v1/runtime/overview"
          target="_blank"
          class="text-sm text-muted-foreground hover:text-primary flex items-center gap-1"
        >
          查看完整 API
          <ExternalLink class="w-3 h-3" />
        </a>
      </div>
    </CardHeader>
    <CardContent>
      <div class="space-y-2">
        <div
          v-for="(endpoint, index) in apiEndpoints"
          :key="endpoint.path"
          class="flex items-center justify-between p-3 rounded-lg border bg-muted/30"
        >
          <div class="flex items-center gap-3">
            <Badge :class="methodColors[endpoint.method]" class="font-mono text-xs">
              {{ endpoint.method }}
            </Badge>
            <code class="text-sm font-mono">{{ endpoint.path }}</code>
          </div>
          <div class="flex items-center gap-2">
            <span class="text-xs text-muted-foreground hidden md:block">{{ endpoint.description }}</span>
            <Button
              variant="ghost"
              size="icon"
              class="h-8 w-8"
              @click="copyPath(endpoint.path, index)"
            >
              <Check v-if="copiedIndex === index" class="w-4 h-4 text-green-600" />
              <Copy v-else class="w-4 h-4" />
            </Button>
          </div>
        </div>
      </div>
    </CardContent>
  </Card>
</template>
