// vue/src/components/ProjectIntro.vue
<script setup lang="ts">
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Zap, Shield, GitBranch, Settings } from 'lucide-vue-next'

const features = [
  {
    icon: Zap,
    title: '轻量高效',
    description: '基于 Go 语言开发，内存占用低，启动速度快，适合容器化部署',
  },
  {
    icon: Shield,
    title: '安全可靠',
    description: '支持写锁机制，防止并发写入冲突，数据安全有保障',
  },
  {
    icon: GitBranch,
    title: '多环境管理',
    description: '支持多环境、多渠道配置管理，轻松应对复杂的业务场景',
  },
  {
    icon: Settings,
    title: '丰富类型',
    description: '支持文本、数字、布尔、JSON、图片等多种配置类型',
  },
]
</script>

<template>
  <Card>
    <CardHeader>
      <CardTitle class="text-lg">项目特性</CardTitle>
    </CardHeader>
    <CardContent>
      <div class="grid grid-cols-2 gap-4">
        <div
          v-for="feature in features"
          :key="feature.title"
          class="p-4 rounded-lg border bg-muted/30"
        >
          <div class="flex items-center gap-3 mb-2">
            <div class="p-2 rounded-md bg-primary/10">
              <component :is="feature.icon" class="w-4 h-4 text-primary" />
            </div>
            <h3 class="font-medium text-sm">{{ feature.title }}</h3>
          </div>
          <p class="text-xs text-muted-foreground">{{ feature.description }}</p>
        </div>
      </div>
    </CardContent>
  </Card>
</template>

// react/components/project-intro.tsx
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import {
  Layers,
  GitBranch,
  Zap,
  ArrowRightLeft,
  FolderOpen,
} from "lucide-react"

const capabilities = [
  {
    icon: Layers,
    title: "环境隔离",
    description: "支持 dev/test/prod 等多环境配置隔离",
  },
  {
    icon: GitBranch,
    title: "渠道管理",
    description: "支持多条渠道并行，满足 A/B 测试",
  },
  {
    icon: Zap,
    title: "实时与静态",
    description: "提供实时接口和静态资源包导出",
  },
  {
    icon: ArrowRightLeft,
    title: "配置迁移",
    description: "一键导出/导入，快速环境同步",
  },
  {
    icon: FolderOpen,
    title: "资源管理",
    description: "集中管理静态资源，自动生成 URL",
  },
]

export function ProjectIntro() {
  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="text-lg">项目简介</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-muted-foreground leading-relaxed">
            <strong className="text-foreground">虹桥计划（Rainbow Bridge）</strong>
            是一个轻量级、自部署的前端资源配置中台，专为多环境、多渠道场景设计。
          </p>
          <p className="text-muted-foreground leading-relaxed">
            基于 <Badge variant="secondary">CloudWeGo Hertz</Badge> 框架构建，支持
            SQLite/MySQL/PostgreSQL 数据库，开箱即用。
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="text-lg">核心能力</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {capabilities.map((cap) => (
              <div
                key={cap.title}
                className="flex items-start gap-3 p-3 rounded-lg border bg-card hover:bg-accent/50 transition-colors"
              >
                <div className="p-2 rounded-md bg-primary/10">
                  <cap.icon className="w-4 h-4 text-primary" />
                </div>
                <div>
                  <h4 className="font-medium text-sm">{cap.title}</h4>
                  <p className="text-xs text-muted-foreground mt-1">
                    {cap.description}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
