// vue/src/components/RuntimeConfig.vue
<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { Copy, Check, RefreshCw, Download, Loader2 } from 'lucide-vue-next'
import { useEnvironmentStore } from '@/stores/environment'
import { configApi } from '@/lib/api/config'
import { runtimeApi } from '@/lib/api/runtime'
import { fromApiConfig } from '@/lib/api/transformers'
import { CONFIG_TYPE_META, type ConfigItem } from '@/lib/types'
import { toast } from 'vue-sonner'

const environmentStore = useEnvironmentStore()

const selectedEnv = ref<string>('')
const selectedPipeline = ref<string>('')
const configs = ref<ConfigItem[]>([])
const loading = ref(false)
const copiedId = ref<string | null>(null)
const exporting = ref(false)

const environments = computed(() => environmentStore.environments)

const selectedEnvData = computed(() => 
  environments.value.find(e => e.key === selectedEnv.value)
)

const pipelines = computed(() => selectedEnvData.value?.pipelines || [])

const fetchConfigs = async () => {
  if (!selectedEnv.value || !selectedPipeline.value) {
    configs.value = []
    return
  }
  
  loading.value = true
  try {
    const response = await configApi.list({
      environment_key: selectedEnv.value,
      pipeline_key: selectedPipeline.value,
    })
    configs.value = response.list.map(fromApiConfig)
  } catch (e) {
    console.error('获取配置列表失败:', e)
    toast.error('获取配置列表失败')
  } finally {
    loading.value = false
  }
}

const handleEnvChange = (value: string) => {
  selectedEnv.value = value
  selectedPipeline.value = ''
  configs.value = []
}

const handlePipelineChange = (value: string) => {
  selectedPipeline.value = value
}

const handleRefresh = () => {
  fetchConfigs()
}

const handleExport = async () => {
  if (!selectedEnv.value || !selectedPipeline.value) return
  
  setExporting(true)
  try {
    const blob = await runtimeApi.exportStatic(selectedEnv.value, selectedPipeline.value)
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `config-${selectedEnv.value}-${selectedPipeline.value}.zip`
    a.click()
    URL.revokeObjectURL(url)
    toast.success('导出成功')
  } catch {
    const data = JSON.stringify(configs.value, null, 2)
    const blob = new Blob([data], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `config-${selectedEnv.value}-${selectedPipeline.value}.json`
    a.click()
    URL.revokeObjectURL(url)
    toast.success('已导出为 JSON 格式')
  } finally {
    setExporting(false)
  }
}

const setExporting = (value: boolean) => {
  exporting.value = value
}

const handleCopy = async (content: string, id: string) => {
  await navigator.clipboard.writeText(content)
  copiedId.value = id
  toast.success('已复制到剪贴板')
  setTimeout(() => {
    copiedId.value = null
  }, 2000)
}

watch(selectedPipeline, () => {
  if (selectedPipeline.value) {
    fetchConfigs()
  }
})

onMounted(() => {
  environmentStore.fetchOverview()
})
</script>

<template>
  <Card>
    <CardHeader>
      <CardTitle class="text-lg">运行时配置</CardTitle>
    </CardHeader>
    <CardContent class="space-y-4">
      <div class="flex flex-wrap items-end gap-4">
        <div class="space-y-2">
          <label class="text-sm font-medium text-foreground">环境:</label>
          <Select 
            :model-value="selectedEnv" 
            @update:model-value="handleEnvChange"
            :disabled="environmentStore.loading"
          >
            <SelectTrigger class="w-48">
              <SelectValue :placeholder="environmentStore.loading ? '加载中...' : '选择环境'" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem 
                v-for="env in environments" 
                :key="env.key" 
                :value="env.key"
              >
                {{ env.name }}
              </SelectItem>
            </SelectContent>
          </Select>
        </div>

        <div class="space-y-2">
          <label class="text-sm font-medium text-foreground">渠道:</label>
          <Select 
            :model-value="selectedPipeline"
            @update:model-value="handlePipelineChange"
            :disabled="!selectedEnv"
          >
            <SelectTrigger class="w-48">
              <SelectValue placeholder="选择渠道" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem 
                v-for="pipeline in pipelines" 
                :key="pipeline.key" 
                :value="pipeline.key"
              >
                {{ pipeline.name }}
              </SelectItem>
            </SelectContent>
          </Select>
        </div>

        <Button
          @click="handleRefresh"
          :disabled="!selectedEnv || !selectedPipeline || loading"
        >
          <RefreshCw :class="['w-4 h-4 mr-2', { 'animate-spin': loading }]" />
          刷新配置
        </Button>

        <Button
          variant="outline"
          @click="handleExport"
          :disabled="configs.length === 0 || exporting"
        >
          <Loader2 v-if="exporting" class="w-4 h-4 mr-2 animate-spin" />
          <Download v-else class="w-4 h-4 mr-2" />
          导出静态资源
        </Button>
      </div>

      <div class="border rounded-lg overflow-hidden">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead class="w-48">名称</TableHead>
              <TableHead class="w-40">别名</TableHead>
              <TableHead class="w-24">类型</TableHead>
              <TableHead>内容</TableHead>
              <TableHead class="w-20">操作</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow v-if="loading">
              <TableCell colspan="5" class="text-center py-8">
                <RefreshCw class="w-5 h-5 animate-spin mx-auto text-muted-foreground" />
                <span class="text-sm text-muted-foreground mt-2 block">
                  加载中...
                </span>
              </TableCell>
            </TableRow>
            <TableRow v-else-if="!selectedEnv || !selectedPipeline">
              <TableCell colspan="5" class="text-center py-8 text-muted-foreground">
                请选择环境和渠道查看配置
              </TableCell>
            </TableRow>
            <TableRow v-else-if="configs.length === 0">
              <TableCell colspan="5" class="text-center py-8 text-muted-foreground">
                当前环境和渠道下暂无配置
              </TableCell>
            </TableRow>
            <TableRow v-else v-for="config in configs" :key="config.id">
              <TableCell class="font-mono text-sm">
                {{ config.name }}
              </TableCell>
              <TableCell class="text-muted-foreground">
                {{ config.alias }}
              </TableCell>
              <TableCell>
                <Badge
                  variant="secondary"
                  :class="CONFIG_TYPE_META[config.type]?.color || ''"
                >
                  {{ CONFIG_TYPE_META[config.type]?.label || config.type }}
                </Badge>
              </TableCell>
              <TableCell class="font-mono text-sm max-w-xs truncate">
                {{ config.content }}
              </TableCell>
              <TableCell>
                <Button
                  variant="ghost"
                  size="icon"
                  @click="handleCopy(config.content, config.id)"
                >
                  <Check v-if="copiedId === config.id" class="w-4 h-4 text-green-600" />
                  <Copy v-else class="w-4 h-4" />
                </Button>
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
    </CardContent>
  </Card>
</template>

// react/components/runtime-config.tsx
"use client"

import { useState } from "react"
import { RefreshCw, Download, Copy, Check, Loader2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { useRuntimeOverview } from "@/hooks/use-environments"
import { useConfigs } from "@/hooks/use-configs"
import { runtimeApi } from "@/lib/api/runtime"
import { CONFIG_TYPE_META } from "@/lib/types"
import { toast } from "sonner"

export function RuntimeConfig() {
  const [selectedEnv, setSelectedEnv] = useState<string>("")
  const [selectedPipeline, setSelectedPipeline] = useState<string>("")
  const [copiedId, setCopiedId] = useState<string | null>(null)
  const [exporting, setExporting] = useState(false)

  // 获取环境和渠道数据
  const { data: environments = [], isLoading: isEnvLoading } = useRuntimeOverview()

  // 获取当前选中环境的渠道
  const selectedEnvData = environments.find((e) => e.key === selectedEnv)
  const pipelines = selectedEnvData?.pipelines || []

  // 获取配置列表
  const {
    data: configs = [],
    isLoading: isConfigsLoading,
    refetch,
  } = useConfigs(selectedEnv, selectedPipeline)

  const handleEnvChange = (value: string) => {
    setSelectedEnv(value)
    setSelectedPipeline("")
  }

  const handleRefresh = () => {
    if (!selectedEnv || !selectedPipeline) return
    refetch()
  }

  const handleExport = async () => {
    if (!selectedEnv || !selectedPipeline) return
    setExporting(true)
    try {
      const blob = await runtimeApi.exportStatic(selectedEnv, selectedPipeline)
      const url = URL.createObjectURL(blob)
      const a = document.createElement("a")
      a.href = url
      a.download = `config-${selectedEnv}-${selectedPipeline}.zip`
      a.click()
      URL.revokeObjectURL(url)
      toast.success("导出成功")
    } catch (error) {
      // 如果静态导出失败，降级为导出 JSON
      const data = JSON.stringify(configs, null, 2)
      const blob = new Blob([data], { type: "application/json" })
      const url = URL.createObjectURL(blob)
      const a = document.createElement("a")
      a.href = url
      a.download = `config-${selectedEnv}-${selectedPipeline}.json`
      a.click()
      URL.revokeObjectURL(url)
      toast.success("已导出为 JSON 格式")
    } finally {
      setExporting(false)
    }
  }

  const handleCopy = async (content: string, id: string) => {
    await navigator.clipboard.writeText(content)
    setCopiedId(id)
    setTimeout(() => setCopiedId(null), 2000)
  }

  const loading = isConfigsLoading

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-lg">运行时配置</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex flex-wrap items-end gap-4">
          <div className="space-y-2">
            <label className="text-sm font-medium text-foreground">环境:</label>
            <Select value={selectedEnv} onValueChange={handleEnvChange} disabled={isEnvLoading}>
              <SelectTrigger className="w-48">
                <SelectValue placeholder={isEnvLoading ? "加载中..." : "选择环境"} />
              </SelectTrigger>
              <SelectContent>
                {environments.map((env) => (
                  <SelectItem key={env.key} value={env.key}>
                    {env.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <label className="text-sm font-medium text-foreground">渠道:</label>
            <Select
              value={selectedPipeline}
              onValueChange={setSelectedPipeline}
              disabled={!selectedEnv}
            >
              <SelectTrigger className="w-48">
                <SelectValue placeholder="选择渠道" />
              </SelectTrigger>
              <SelectContent>
                {pipelines.map((pipeline) => (
                  <SelectItem key={pipeline.key} value={pipeline.key}>
                    {pipeline.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <Button
            onClick={handleRefresh}
            disabled={!selectedEnv || !selectedPipeline || loading}
          >
            <RefreshCw className={`w-4 h-4 mr-2 ${loading ? "animate-spin" : ""}`} />
            刷新配置
          </Button>

          <Button
            variant="outline"
            onClick={handleExport}
            disabled={configs.length === 0 || exporting}
          >
            {exporting ? (
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
            ) : (
              <Download className="w-4 h-4 mr-2" />
            )}
            导出静态资源
          </Button>
        </div>

        <div className="border rounded-lg overflow-hidden">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-48">名称</TableHead>
                <TableHead className="w-40">别名</TableHead>
                <TableHead className="w-24">类型</TableHead>
                <TableHead>内容</TableHead>
                <TableHead className="w-20">操作</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {loading ? (
                <TableRow>
                  <TableCell colSpan={5} className="text-center py-8">
                    <RefreshCw className="w-5 h-5 animate-spin mx-auto text-muted-foreground" />
                    <span className="text-sm text-muted-foreground mt-2 block">
                      加载中...
                    </span>
                  </TableCell>
                </TableRow>
              ) : !selectedEnv || !selectedPipeline ? (
                <TableRow>
                  <TableCell
                    colSpan={5}
                    className="text-center py-8 text-muted-foreground"
                  >
                    请选择环境和渠道查看配置
                  </TableCell>
                </TableRow>
              ) : configs.length === 0 ? (
                <TableRow>
                  <TableCell
                    colSpan={5}
                    className="text-center py-8 text-muted-foreground"
                  >
                    当前环境和渠道下暂无配置
                  </TableCell>
                </TableRow>
              ) : (
                configs.map((config) => (
                  <TableRow key={config.id}>
                    <TableCell className="font-mono text-sm">
                      {config.name}
                    </TableCell>
                    <TableCell className="text-muted-foreground">
                      {config.alias}
                    </TableCell>
                    <TableCell>
                      <Badge
                        variant="secondary"
                        className={CONFIG_TYPE_META[config.type as keyof typeof CONFIG_TYPE_META]?.color || ""}
                      >
                        {CONFIG_TYPE_META[config.type as keyof typeof CONFIG_TYPE_META]?.label || config.type}
                      </Badge>
                    </TableCell>
                    <TableCell className="font-mono text-sm max-w-xs truncate">
                      {config.content}
                    </TableCell>
                    <TableCell>
                      <Button
                        variant="ghost"
                        size="icon"
                        onClick={() => handleCopy(config.content, config.id)}
                      >
                        {copiedId === config.id ? (
                          <Check className="w-4 h-4 text-green-600" />
                        ) : (
                          <Copy className="w-4 h-4" />
                        )}
                      </Button>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </div>
      </CardContent>
    </Card>
  )
}
